In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/raw/Africa_aggregated_data_from_ACLED.csv",sep=";", on_bad_lines='skip')

In [8]:
df.head()

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE
0,23-October-2004,Northern Africa,Algeria,Adrar,Battles,Armed clash,1,2,NaN,Political violence,47.0,"26,4839","-1,388"
1,23-April-2005,Northern Africa,Algeria,Adrar,Battles,Armed clash,1,0,NaN,Political violence,47.0,"26,4839","-1,388"
2,25-June-2005,Northern Africa,Algeria,Adrar,Battles,Armed clash,1,14,NaN,Political violence,47.0,"26,4839","-1,388"
3,13-December-2008,Northern Africa,Algeria,Adrar,Battles,Armed clash,1,3,NaN,Political violence,47.0,"26,4839","-1,388"
4,18-April-2009,Northern Africa,Algeria,Adrar,Battles,Armed clash,1,2,NaN,Political violence,47.0,"26,4839","-1,388"

In [12]:
aes_country = ['Mali', 'Burkina Faso', 'Niger']
df_aes = df[df['COUNTRY'].isin(aes_country)].copy()

In [15]:
df_aes

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE
13024,01-July-2006,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,9,NaN,Political violence,3738.0,"12,4738","-3,5892"
13025,14-May-2011,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,2,NaN,Political violence,3738.0,"12,4738","-3,5892"
13026,08-July-2017,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,2,1,11709.0,Political violence,3738.0,"12,4738","-3,5892"
13027,26-August-2017,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,1,14188.0,Political violence,3738.0,"12,4738","-3,5892"
13028,23-September-2017,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,0,2664.0,Political violence,3738.0,"12,4738","-3,5892"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
140925,10-May-2008,Western Africa,Niger,Zinder,Violence against civilians,Abduction/forced disappearance,1,0,NaN,Political violence,3836.0,"15,2189","9,715"
140926,19-January-2008,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,3,NaN,Political violence,3836.0,"15,2189","9,715"
140927,11-August-2012,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,0,NaN,Political violence,3836.0,"15,2189","9,715"
140928,06-August-2022,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,0,1851.0,Political violence,3836.0,"15,2189","9,715"
140929,03-September-2022,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,0,2084.0,Political violence,3836.0,"15,2189","9,715"

In [17]:
df_aes.shape

(21198, 13)

In [18]:
df_aes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21198 entries, 13024 to 140929
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   WEEK                 21198 non-null  object
 1   REGION               21198 non-null  object
 2   COUNTRY              21198 non-null  object
 3   ADMIN1               21198 non-null  object
 4   EVENT_TYPE           21198 non-null  object
 5   SUB_EVENT_TYPE       21198 non-null  object
 6   EVENTS               21198 non-null  int64
 7   FATALITIES           21198 non-null  int64
 8   POPULATION_EXPOSURE  15224 non-null  float64
 9   DISORDER_TYPE        21198 non-null  object
 10  ID                   21198 non-null  float64
 11  CENTROID_LATITUDE    21198 non-null  object
 12  CENTROID_LONGITUDE   21198 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 2.3+ MB

In [19]:
df_aes.isnull().sum()

WEEK                      0
REGION                    0
COUNTRY                   0
ADMIN1                    0
EVENT_TYPE                0
SUB_EVENT_TYPE            0
EVENTS                    0
FATALITIES                0
POPULATION_EXPOSURE    5974
DISORDER_TYPE             0
ID                        0
CENTROID_LATITUDE         0
CENTROID_LONGITUDE        0
dtype: int64

In [20]:
print(df_aes[df_aes['POPULATION_EXPOSURE'].isnull()]['COUNTRY'].value_counts())

COUNTRY
Mali            2655
Burkina Faso    1956
Niger           1363
Name: count, dtype: int64

In [21]:
print(df_aes['EVENT_TYPE'].value_counts())

EVENT_TYPE
Violence against civilians    5664
Strategic developments        4691
Battles                       4647
Explosions/Remote violence    3442
Protests                      2020
Riots                          734
Name: count, dtype: int64

In [22]:
pd.crosstab(df_aes['COUNTRY'], df_aes['EVENT_TYPE'])

EVENT_TYPE,Battles,Explosions/Remote violence,Protests,Riots,Strategic developments,Violence against civilians
COUNTRY,,,,,,
Burkina Faso,1825,1346,1134,325,1590,1995
Mali,2019,1785,651,252,2014,2482
Niger,803,311,235,157,1087,1187

In [26]:
df_aes['WEEK'] = pd.to_datetime(df_aes['WEEK'], errors='coerce')
df_aes['YEAR'] = df_aes['WEEK'].dt.year

In [27]:
df_aes

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE,year,YEAR
13024,2006-07-01,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,9,NaN,Political violence,3738.0,"12,4738","-3,5892",2006,2006
13025,2011-05-14,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,2,NaN,Political violence,3738.0,"12,4738","-3,5892",2011,2011
13026,2017-07-08,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,2,1,11709.0,Political violence,3738.0,"12,4738","-3,5892",2017,2017
13027,2017-08-26,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,1,14188.0,Political violence,3738.0,"12,4738","-3,5892",2017,2017
13028,2017-09-23,Western Africa,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,0,2664.0,Political violence,3738.0,"12,4738","-3,5892",2017,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140925,2008-05-10,Western Africa,Niger,Zinder,Violence against civilians,Abduction/forced disappearance,1,0,NaN,Political violence,3836.0,"15,2189","9,715",2008,2008
140926,2008-01-19,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,3,NaN,Political violence,3836.0,"15,2189","9,715",2008,2008
140927,2012-08-11,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,0,NaN,Political violence,3836.0,"15,2189","9,715",2012,2012
140928,2022-08-06,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,0,1851.0,Political violence,3836.0,"15,2189","9,715",2022,2022
140929,2022-09-03,Western Africa,Niger,Zinder,Violence against civilians,Attack,1,0,2084.0,Political violence,3836.0,"15,2189","9,715",2022,2022

In [33]:
df_aes.drop('year',axis = 1,inplace= True)

In [34]:
df_aes = df_aes.reset_index(drop=True)

In [35]:
df_aes.describe()

,WEEK,EVENTS,FATALITIES,POPULATION_EXPOSURE,ID,YEAR
count,21198,21198.000000,21198.000000,1.522400e+04,21198.000000,21198.000000
mean,2021-09-20 11:00:41.777526016,1.630626,3.639023,2.861395e+04,3782.836164,2021.231295
min,1997-01-04 00:00:00,1.000000,0.000000,1.000000e+00,3734.000000,1997.000000
25%,2020-04-11 00:00:00,1.000000,0.000000,2.459750e+03,3742.000000,2020.000000
50%,2022-08-20 00:00:00,1.000000,0.000000,7.571500e+03,3798.000000,2022.000000
75%,2024-04-20 00:00:00,2.000000,3.000000,2.456475e+04,3803.000000,2024.000000
max,2026-03-14 00:00:00,28.000000,399.000000,1.235074e+06,3838.000000,2026.000000
std,NaN,1.267195,11.674554,7.106330e+04,36.483105,3.956091

In [36]:
print(df_aes['COUNTRY'].value_counts())

COUNTRY
Mali            9203
Burkina Faso    8215
Niger           3780
Name: count, dtype: int64

In [37]:
print(df_aes.groupby('COUNTRY')['FATALITIES'].sum())

COUNTRY
Burkina Faso    34087
Mali            30486
Niger           12567
Name: FATALITIES, dtype: int64

In [ ]:
df_aes = df_aes.drop(columns=['POPULATION_EXPOSURE','REGION'])

In [42]:
df_aes

,WEEK,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE,YEAR
0,2006-07-01,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,9,Political violence,3738.0,"12,4738","-3,5892",2006
1,2011-05-14,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,2,Political violence,3738.0,"12,4738","-3,5892",2011
2,2017-07-08,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,2,1,Political violence,3738.0,"12,4738","-3,5892",2017
3,2017-08-26,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,1,Political violence,3738.0,"12,4738","-3,5892",2017
4,2017-09-23,Burkina Faso,Boucle du Mouhoun,Battles,Armed clash,1,0,Political violence,3738.0,"12,4738","-3,5892",2017
...,...,...,...,...,...,...,...,...,...,...,...,...
21193,2008-05-10,Niger,Zinder,Violence against civilians,Abduction/forced disappearance,1,0,Political violence,3836.0,"15,2189","9,715",2008
21194,2008-01-19,Niger,Zinder,Violence against civilians,Attack,1,3,Political violence,3836.0,"15,2189","9,715",2008
21195,2012-08-11,Niger,Zinder,Violence against civilians,Attack,1,0,Political violence,3836.0,"15,2189","9,715",2012
21196,2022-08-06,Niger,Zinder,Violence against civilians,Attack,1,0,Political violence,3836.0,"15,2189","9,715",2022
21197,2022-09-03,Niger,Zinder,Violence against civilians,Attack,1,0,Political violence,3836.0,"15,2189","9,715",2022